export const MODULE_MATURITY = Object.freeze({
  optimized: {
    label: 'Optimized',
    shortLabel: 'OPT',
    description: 'Primary workflow is hardened, regression-checked, and tuned for routine production use.',
    badgeClass: 'border-emerald-300 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-950/70 dark:text-emerald-300',
  },
  production: {
    label: 'Production',
    shortLabel: 'LIVE',
    description: 'Production-ready workflow with standard safeguards and monitoring.',
    badgeClass: 'border-sky-300 bg-sky-50 text-sky-700 dark:border-sky-800 dark:bg-sky-950/70 dark:text-sky-300',
  },
  beta: {
    label: 'Beta',
    shortLabel: 'BETA',
    description: 'Usable with administrator review while edge cases, scale, or integrations are still being hardened.',
    badgeClass: 'border-amber-300 bg-amber-50 text-amber-800 dark:border-amber-800 dark:bg-amber-950/70 dark:text-amber-300',
  },
});

export const ADMIN_CATEGORIES = Object.freeze([
  {
    key: 'Records & Registers',
    title: 'Records & Registers',
    desc: 'Student admission records, official ledgers, rosters, certificates, ID cards and school-based assessments',
    iconName: 'BarChart2',
    color: 'text-amber-500 dark:text-amber-400',
    bg: 'bg-amber-500/10 dark:bg-amber-500/20',
  },
  {
    key: 'Academics & Controls',
    title: 'Academics & Controls',
    desc: 'Session settings, subjects, practicals award rolls, student attendance and class roll numbers',
    iconName: 'Settings',
    color: 'text-emerald-500 dark:text-emerald-400',
    bg: 'bg-emerald-500/10 dark:bg-emerald-500/20',
  },
  {
    key: 'Operations & Automation',
    title: 'Operations & Automation',
    desc: 'Duplicate merger, communications, fee accounts, staff tax & salaries, website CMS and JKBOSE sync',
    iconName: 'Layers',
    color: 'text-indigo-500 dark:text-indigo-400',
    bg: 'bg-indigo-500/10 dark:bg-indigo-500/20',
  },
  {
    key: 'Quick Actions',
    title: 'Quick Actions',
    desc: 'Rapid inline cell edit toggle and bulk data ingestion & photo suite',
    iconName: 'Zap',
    color: 'text-violet-500 dark:text-violet-400',
    bg: 'bg-violet-500/10 dark:bg-violet-500/20',
  },
]);

export const ADMIN_MODULE_CATALOG = Object.freeze([
  // CATEGORY 1: Records & Registers (7 Modules)
  {
    id: 'reports',
    label: 'Student Records & Reports',
    shortLabel: 'Records',
    description: 'Review, approve, edit, export and audit student records',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Exact-document mutations, protected bulk actions, recycle recovery and regression checks are in place.',
    launcher: true,
    isNew: false,
    aliases: ['reports'],
    keywords: ['student records', 'admissions', 'approval', 'pending admission', 'enrolment', 'intake', 'recycle bin', 'restore student', 'drop student', 'excel export', 'pdf print', 'search student', 'form review', 'applicant', 'student profile'],
  },
  {
    id: 'admRegisterSuite',
    label: 'Admission Register & Sent-up Suite',
    shortLabel: 'Admission Register',
    description: 'Official ledger, JKBOSE sent-up roll, IDs and admission dates',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'O(1) indexed lookups, configurable sent-up register columns, cleaned examination records, and regression-checked ledger layouts are in place.',
    launcher: true,
    isNew: true,
    aliases: ['admRegisterSuite', 'admissionRegister'],
    keywords: ['board', 'jkbose', 'sent up', 'sent-up roll', 'admission register', 'official ledger', 'board registration', 'board roll', 'state board', 'class 10 sent up', 'class 11 sent up', 'class 12 sent up', 'matric sent up', 'permanent ledger', 'serial numbers', 'admission dates'],
  },
  {
    id: 'analyticsReports',
    label: 'Analytics & Statistical Reports Suite',
    shortLabel: 'Analytics',
    description: 'Class enrollment analysis, stream intake metrics, gender breakdown, subject distribution, and official JKBOSE subject-wise roll return statements',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Interactive statistical dashboard, class-wise distribution, gender breakdown, and integrated JKBOSE subject roll return statement with automatic range compression.',
    launcher: true,
    isNew: true,
    aliases: ['analyticsReports', 'analytics', 'statisticalReports', 'jkboseSubjectRolls', 'subjectRolls', 'jkboseRolls'],
    keywords: ['board', 'jkbose', 'subject roll returns', 'roll statement', 'analytics', 'statistics', 'intake metrics', 'stream distribution', 'gender ratio', 'boys girls', 'enrollment charts', 'bose returns', 'range compression', 'class distribution'],
  },
  {
    id: 'directEntry',
    label: 'Express Direct Record Entry',
    shortLabel: 'Direct Entry',
    description: 'Add a single student application directly into active intake with immediate validation & duplicate guard',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Single-record immediate ingestion with instant validation, live duplicate checking and direct intake registry insertion.',
    launcher: true,
    isNew: true,
    aliases: ['directEntry', 'directEntryAction', 'ingestion'],
    keywords: ['direct admission', 'new admission', 'add student', 'manual entry', 'express entry', 'walk-in', 'single student', 'quick registration', 'enroll student', 'new intake', 'applicant entry'],
  },
  {
    id: 'customRoster',
    label: 'Student Rosters & Registers',
    shortLabel: 'Rosters',
    description: 'Custom lists, fee sheets, class registers and tabular records',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Canonical photo resolution, configurable columns and print/export safeguards are regression-checked.',
    launcher: true,
    isNew: true,
    aliases: ['customRoster', 'docStudio', 'roster'],
    keywords: ['roster', 'student lists', 'class list', 'photo roster', 'fee sheet', 'custom columns', 'class register', 'tabular print', 'subject list', 'stream list', 'excel export', 'pdf roster', 'printable list', 'spreadsheet'],
  },
  {
    id: 'officialLetter',
    label: 'Official Letterhead Writer',
    shortLabel: 'Letterhead',
    description: 'Compose, format and print official institutional letters',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Multi-key Gemini AI integration, local draft autosave resilience, document history auto-archiving, and print audit logging are regression-checked.',
    launcher: true,
    isNew: true,
    aliases: ['officialLetter', 'letterhead'],
    keywords: ['letterhead', 'official letter', 'compose letter', 'ai letter writer', 'gemini letter', 'formal letter', 'correspondence', 'office order', 'circular', 'memo', 'requisition', 'print letter', 'school letterhead'],
  },
  {
    id: 'certStudio',
    label: 'Student Bonafides & Certificates',
    shortLabel: 'Certificates',
    description: 'Generate bonafide, character, DOB and achievement certificates',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Authoritative serial generation, QR verification URL generation, DOB-inwords interpolation, and batch issuance audit trails are in place.',
    launcher: true,
    isNew: true,
    aliases: ['certStudio', 'certificate'],
    keywords: ['certificate', 'bonafide', 'character certificate', 'provisional certificate', 'dob certificate', 'birth certificate', 'slc', 'transfer certificate', 'school leaving', 'discharge certificate', 'qr verification', 'board certificate', 'student certificates'],
  },
  {
    id: 'idCards',
    label: 'Student ID Card Studio',
    shortLabel: 'ID Cards',
    description: 'Filter, design, batch-prepare and print verified student identity cards',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Strict cohort filters, stable selections, bounded concurrent photo preparation and print-range safeguards are regression-checked.',
    launcher: true,
    isNew: true,
    aliases: ['idCards', 'idcard'],
    keywords: ['id cards', 'identity card', 'id card studio', 'student badge', 'smart card', 'id card print', 'photo id', 'batch id cards', 'barcode', 'qr id card', 'student pass', 'card design'],
  },
  {
    id: 'beneficiaryStudio',
    label: 'Beneficiary & Sanction Orders Studio',
    shortLabel: 'Beneficiaries',
    description: 'Mutual benefit fund rolls, bank debit orders, poor fund sanctions and student beneficiary lists with bulk reg no fetch',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Multi-class bulk reg no ingestion, custom columns with auto-sum calculation, bank debit directives, committee signatures, and 1-click exports are regression-checked.',
    launcher: true,
    isNew: true,
    aliases: ['beneficiaryStudio', 'beneficiaryOrders', 'sanctionOrders', 'beneficiaries', 'beneficiaryList'],
    keywords: ['beneficiary', 'mutual benefit fund', 'bank debit order', 'sanction order', 'poor fund', 'financial assistance', 'scholarship', 'bank transfer', 'disbursement', 'account numbers', 'ifsc', 'committee signatures', 'beneficiary list', 'fund rolls'],
  },
  {
    id: 'gkTest',
    label: 'School Based Assessment',
    shortLabel: 'Assessments',
    description: 'School evaluations (Pre-Board, Unit & Term Tests), teacher assessment approvals, consolidated gazette, admit cards & OMR',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Unified school evaluation hub, teacher assessment approvals, automated admit card PDF generation, and audit logging are regression-checked.',
    launcher: true,
    isNew: true,
    aliases: ['gkTest', 'examPrep', 'schoolAssessment', 'schoolAssessments', 'schoolBasedAssessment', 'assessments', 'omr'],
    keywords: ['board', 'pre-board', 'pre board', 'school based assessment', 'golden test', 'unit test', 'term test', 'examinations', 'exams', 'admit cards', 'omr', 'mcq test', 'competitive test', 'gazette', 'results', 'marks', 'teacher approval', 'evaluation', 'test score'],
  },

  // CATEGORY 2: Academics & Controls (5 Modules)
  {
    id: 'controls',
    label: 'System & Admission Controls',
    shortLabel: 'Controls',
    description: 'Class admission windows, academic session year, faculty portals, email automations, cloud storage quota health & annual session rollover',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Atomic session controls, admission window toggles, cloud storage quota health & space reclamation, and audited configuration safeguards.',
    launcher: true,
    isNew: false,
    aliases: ['controls', 'admissionControls', 'systemControls', 'storage', 'quota'],
    keywords: ['admission window', 'admission controls', 'academic session', 'session rollover', 'open admissions', 'close admissions', 'system settings', 'storage quota', 'cloud storage', 'quota health', 'faculty portal switch', 'annual rollover', 'portal controls'],
  },
  {
    id: 'curriculum',
    label: 'Subjects, Streams & Feeder Schools',
    shortLabel: 'Curriculum',
    description: 'Configure streams, compulsory & elective subject pools, admission combination rules & feeder schools registry',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Full admission form dynamic schema sync, subject pool configuration, and feeder schools registry are regression-checked.',
    launcher: true,
    isNew: true,
    aliases: ['curriculum', 'subjects', 'streams', 'feederSchools'],
    keywords: ['curriculum', 'subjects', 'streams', 'subject combinations', 'subject codes', 'feeder schools', 'middle schools', 'medical', 'non-medical', 'arts', 'humanities', 'commerce', 'subject pool', 'electives', 'course structure', 'feeder registry'],
  },
  {
    id: 'practicals',
    label: 'Practicals & Award Rolls',
    shortLabel: 'Practicals',
    description: 'Practical evaluation marks (Internal Assessment & External Practical only), examiners, locking and award rolls',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Validated practical marks bounds, consolidated practical award rolls, spreadsheet reconciliation, and audit logging are regression-checked.',
    launcher: true,
    isNew: false,
    aliases: ['practicals'],
    keywords: ['board', 'practicals', 'practical marks', 'award rolls', 'internal assessment', 'external practical', 'laboratory', 'science practicals', 'examiner', 'examiner signatures', 'practical gazette', 'board award roll', 'physics practical', 'chemistry practical', 'biology practical', 'marks entry'],
  },
  {
    id: 'attendanceMgmt',
    label: 'Student Attendance',
    shortLabel: 'Attendance',
    description: 'Daily attendance registers, entry and reports',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Aggregated attendance tracking, subject-wise grouping, cached register queries, and configuration safeguards are regression-checked.',
    launcher: true,
    isNew: false,
    aliases: ['attendanceMgmt', 'attendance'],
    keywords: ['attendance', 'student attendance', 'daily attendance', 'absent', 'present', 'leave', 'roll call', 'attendance register', 'monthly attendance', 'attendance report', 'defaulter list', 'attendance percentage', 'class attendance'],
  },
  {
    id: 'rollNo',
    label: 'Class Roll Number Manager',
    shortLabel: 'Roll Numbers',
    description: 'Assign, validate and sequence class roll numbers',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Exact-record updates and approved-record safeguards are in place.',
    launcher: true,
    isNew: false,
    aliases: ['rollNo', 'rollNumbers'],
    keywords: ['roll numbers', 'class roll no', 'roll no assigner', 'auto roll number', 'sequence roll numbers', 'roll number manager', 'class rolls', 're-index rolls', 'bulk roll numbers', 'serial roll'],
  },

  // CATEGORY 3: Operations & Automation (6 Modules)
  {
    id: 'mergeStudio',
    label: 'Application Merge & Deduplication',
    shortLabel: 'Merge Studio',
    description: 'Compare and merge duplicate applications by verified identity',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Disjoint-set union clustering, canonical scoring, Recycle Bin safe backup, and audit logging are regression-checked.',
    launcher: true,
    isNew: true,
    aliases: ['mergeStudio', 'merger'],
    keywords: ['merge', 'deduplication', 'duplicate students', 'duplicate applications', 'double admission', 'identity merge', 'clean duplicates', 'merge studio', 'cluster duplicates', 'dedup'],
  },
  {
    id: 'automations',
    label: 'Communications & Automations',
    shortLabel: 'Automations',
    description: 'Group email, parent notifications and delivery logs',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Rich-text group notifications, real-time recipient filtering, test flight previews, and delivery audit logging are regression-checked.',
    launcher: true,
    isNew: false,
    aliases: ['automations', 'emails'],
    keywords: ['communications', 'email', 'group email', 'bulk email', 'parent notifications', 'whatsapp', 'sms', 'broadcast', 'announcements', 'alerts', 'parent message', 'delivery logs', 'cohort broadcast'],
  },
  {
    id: 'funds',
    label: 'Funds & Fee Accounts',
    shortLabel: 'Fee Accounts',
    description: 'Reconciled fee structures, student ledgers and account distribution',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Atomic account configuration, live ledger synchronization and over-distribution safeguards are regression-checked.',
    launcher: true,
    isNew: false,
    aliases: ['funds', 'fees'],
    keywords: ['fees', 'funds', 'fee accounts', 'student ledger', 'fee structure', 'fee receipt', 'dues', 'payment', 'fee concession', 'school funds', 'collection register', 'reconciliation', 'account heads'],
  },
  {
    id: 'accounts',
    label: 'School Accounts, Salaries & Staff Tax',
    shortLabel: 'Accounts',
    description: 'Staff income tax calculator, salary statements, fiscal planning and accounts clerk workflows',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Dedicated accounts clerk workspace, IT calculation engine, tax deductions and salary record management.',
    launcher: true,
    isNew: true,
    aliases: ['accounts', 'salary', 'tax'],
    keywords: ['accounts', 'salary', 'staff salary', 'income tax', 'tax calculator', 'tds', 'deductions', 'nps', 'gp fund', 'form 16', 'accounts clerk', 'salary statements', 'pay bill', 'fiscal planning'],
  },
  {
    id: 'cms',
    label: 'Website CMS & Administration',
    shortLabel: 'Website CMS',
    description: 'Public website content, hero slideshow, notices, custom pages and recycle bin',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Public and private website controls, notices, slideshow, custom pages, and central recycle bin.',
    launcher: true,
    isNew: true,
    aliases: ['cms', 'websiteCms', 'heroButtons'],
    keywords: ['website', 'cms', 'homepage', 'notices', 'circulars', 'slider', 'hero banner', 'photo gallery', 'school website', 'announcements', 'public pages', 'news', 'content management', 'website bin'],
  },
  {
    id: 'achievementsCms',
    label: 'Achievements & Hall of Fame CMS',
    shortLabel: 'Achievements CMS',
    description: 'Publish and spotlight student academic awards, JKBOSE top ranks, UT positions, NEET/JEE and sports honors',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Student fast-lookup, UT position spotlight, automated photo resolution, and cross-tab real-time sync.',
    launcher: true,
    isNew: true,
    aliases: ['achievementsCms', 'achievements', 'hallOfFame', 'achievements_cms'],
    keywords: ['achievements', 'hall of fame', 'ut positions', 'top ranks', 'toppers', 'neet', 'jee', 'cuet', 'sports', 'jkbose position', 'medals', 'awards', 'merit', 'honors', 'trophies', 'cms'],
  },
  {
    id: 'boardSync',
    label: 'Student Data & Board Ingestion Hub',
    shortLabel: 'Board Ingestion',
    description: 'Bulk overwrite and express entry for student admission fields with verified JKBOSE board data and AI tools',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'End-to-end full page workspace with authoritative field classification, Board Reg matching, protected class roll numbers, and 30-day rollback memory.',
    launcher: true,
    isNew: true,
    aliases: ['boardSync', 'jkboseSync', 'ingestionHub', 'bulkOverwrite'],
    keywords: ['board', 'jkbose', 'board sync', 'board ingestion', 'gazette import', 'board data', 'jkbose gazette', 'bulk overwrite', 'board roll', 'board reg no', 'verified board records', 'ai data extraction', 'state board', 'import gazette'],
  },
  {
    id: 'activityAudit',
    label: 'Activity Audit & Dispute Trail',
    shortLabel: 'Activity Audit',
    description: 'Track, inspect, and verify immutable audit trails across student, teacher & admin actions for dispute resolution',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'On-demand paginated reads with multi-filter query indexing to minimize Firestore costs.',
    launcher: true,
    isNew: true,
    aliases: ['activityAudit', 'auditLogs', 'activityLogs'],
    keywords: ['audit', 'activity audit', 'audit logs', 'activity logs', 'history', 'change history', 'who did what', 'dispute trail', 'security logs', 'tracking', 'action history', 'investigation', 'audit trail'],
  },
  {
    id: 'googleContacts',
    label: 'Google Contacts Bulk Exporter',
    shortLabel: 'Google Contacts',
    description: 'Bulk export student cohorts to Google Contacts CSV with standard naming & parent records',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Full legacy logic ported with board subject abbreviations, 38 Google headers, and 1-click import guide.',
    launcher: true,
    isNew: true,
    aliases: ['googleContacts', 'bulkContacts', 'contactSaver'],
    keywords: ['google contacts', 'contacts export', 'phone contacts', 'parent phonebook', 'whatsapp contacts', 'csv contacts', 'contact saver', 'phone numbers', 'mobile export', 'address book'],
  },
  {
    id: 'staff',
    label: 'Staff & Permissions',
    shortLabel: 'Staff Access',
    description: 'Manage Teachers and Standard Admins, their designations, and module-scoped access; Super Admin authority remains protected',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Server-enforced role governance: delegated Standard Admins can manage only Teacher/Admin accounts and only modules assigned to themselves.',
    launcher: true,
    isNew: true,
    aliases: ['staff', 'staffPermissions', 'permissions', 'adminMgmt'],
    keywords: ['staff', 'teachers', 'faculty', 'permissions', 'roles', 'rbac', 'access control', 'administrators', 'superadmin', 'passwords', 'staff accounts', 'designations', 'user management', 'privileges'],
  },

  // CATEGORY 4: Quick Actions & Ingestion Tools (2 Tools)
  {
    id: 'quickCellEdit',
    label: 'Quick Cell Edit Mode',
    shortLabel: 'Cell Edit',
    description: 'Directly click and update table cells in student records',
    category: 'Quick Actions',
    maturity: 'optimized',
    maturityNote: 'Inline quick cell modification with automatic audit logging.',
    launcher: false,
    isQuickAction: true,
    isNew: true,
    aliases: ['quickCellEdit'],
    keywords: ['quick cell edit', 'inline edit', 'edit table', 'fast edit', 'cell edit', 'quick update', 'rapid cell edit'],
  },
  {
    id: 'bulkToolsAction',
    label: 'Bulk Tools & Ingestion Suite',
    shortLabel: 'Bulk Tools',
    description: 'Bulk table actions, status updates, photo batch exports and data tools',
    category: 'Quick Actions',
    maturity: 'optimized',
    maturityNote: 'Bulk batch updater with column mapping and rollback protection.',
    launcher: false,
    isQuickAction: true,
    isNew: true,
    aliases: ['bulkToolsAction', 'bulkTools', 'bulk'],
    keywords: ['bulk tools', 'bulk status', 'batch export', 'photo suite', 'photo export', 'batch photo download', 'data tools', 'bulk actions', 'bulk updater'],
  },
]);

export const ROLE_PRESETS = Object.freeze([
  {
    id: 'full_admin',
    name: 'Full Administrator',
    shortName: 'Full Admin',
    badgeClass: 'bg-indigo-600 text-white',
    desc: 'Access to all 27 administrative modules, tools, and configurations.',
    perms: () => ADMIN_MODULE_CATALOG.map(m => m.id),
  },
  {
    id: 'academic_incharge',
    name: 'Academic & Examination Incharge',
    shortName: 'Academics',
    badgeClass: 'bg-emerald-600 text-white',
    desc: 'Student Records, Admission Register, Subject Rolls, Rosters, Curriculum, Practicals, Attendance, Roll Numbers, Board Sync & Achievements CMS.',
    perms: () => [
      'reports', 'admRegisterSuite', 'customRoster', 'gkTest', 'directEntry',
      'controls', 'curriculum', 'practicals', 'attendanceMgmt', 'rollNo', 'boardSync',
      'analyticsReports', 'achievementsCms', 'quickCellEdit'
    ],
  },
  {
    id: 'records_incharge',
    name: 'Records & Identity Incharge',
    shortName: 'Records',
    badgeClass: 'bg-amber-600 text-white',
    desc: 'Student Records, Rosters, Beneficiary Lists, ID Cards, Certificates, Letterhead, Subject Rolls and Quick Cell Edit.',
    perms: () => [
      'reports', 'admRegisterSuite', 'customRoster', 'beneficiaryStudio', 'officialLetter', 'certStudio', 'directEntry',
      'idCards', 'analyticsReports', 'quickCellEdit'
    ],
  },
  {
    id: 'accounts_clerk',
    name: 'School Accounts & Fee Clerk',
    shortName: 'Accounts',
    badgeClass: 'bg-teal-600 text-white',
    desc: 'School Accounts, Staff Salary/Tax calculations, Funds/Fee Accounts and Beneficiary Sanctions.',
    perms: () => ['accounts', 'funds', 'beneficiaryStudio'],
  },
  {
    id: 'teacher',
    name: 'Faculty / Subject Teacher',
    shortName: 'Teacher',
    badgeClass: 'bg-sky-600 text-white',
    desc: 'Student Attendance registers and Practical Examination award roll submission.',
    perms: () => ['attendanceMgmt', 'practicals'],
  },
]);

export function getModuleMaturity(maturity) {
  return MODULE_MATURITY[maturity] || MODULE_MATURITY.beta;
}

export function getAdminModule(moduleId) {
  return ADMIN_MODULE_CATALOG.find(module => module.id === moduleId) || null;
}

export function getModulesByCategory(categoryKey) {
  return ADMIN_MODULE_CATALOG.filter(module => module.category === categoryKey);
}

export function getAllAdminModuleIds() {
  return ADMIN_MODULE_CATALOG.map(module => module.id);
}
