export const MODULE_MATURITY = Object.freeze({
  optimized: {
    label: 'Optimized',
    shortLabel: 'OPT',
    description: 'Primary workflow is hardened, regression-checked, and tuned for routine production use.',
    badgeClass: 'border-emerald-300 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-950/70 dark:text-emerald-300',
  },
  production: {
    label: 'Production',
    shortLabel: 'LIVE',
    description: 'Production-ready workflow with standard safeguards and monitoring.',
    badgeClass: 'border-sky-300 bg-sky-50 text-sky-700 dark:border-sky-800 dark:bg-sky-950/70 dark:text-sky-300',
  },
  beta: {
    label: 'Beta',
    shortLabel: 'BETA',
    description: 'Usable with administrator review while edge cases, scale, or integrations are still being hardened.',
    badgeClass: 'border-amber-300 bg-amber-50 text-amber-800 dark:border-amber-800 dark:bg-amber-950/70 dark:text-amber-300',
  },
});

export const ADMIN_MODULE_CATALOG = Object.freeze([
  {
    id: 'reports',
    label: 'Student Records & Reports',
    shortLabel: 'Records',
    description: 'Review, approve, edit, export and audit student records',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Exact-document mutations, protected bulk actions, recycle recovery and regression checks are in place.',
    launcher: true,
  },
  {
    id: 'admRegisterSuite',
    label: 'Admission Register & Sent-up Suite',
    shortLabel: 'Admission Register',
    description: 'Official ledger, JKBOSE sent-up roll, IDs and admission dates',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'O(1) indexed lookups, configurable sent-up register columns, cleaned examination records, and regression-checked ledger layouts are in place.',
    launcher: true,
  },
  {
    id: 'customRoster',
    label: 'Student Rosters & Registers',
    shortLabel: 'Rosters',
    description: 'Custom lists, fee sheets, class registers and tabular records',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Canonical photo resolution, configurable columns and print/export safeguards are regression-checked.',
    launcher: true,
  },
  {
    id: 'officialLetter',
    label: 'Official Letterhead Writer',
    shortLabel: 'Letterhead',
    description: 'Compose, format and print official institutional letters',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Multi-key Gemini AI integration, local draft autosave resilience, document history auto-archiving, and print audit logging are regression-checked.',
    launcher: true,
  },
  {
    id: 'certStudio',
    label: 'Student Bonafides & Certificates',
    shortLabel: 'Certificates',
    description: 'Generate bonafide, character, DOB and achievement certificates',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Authoritative serial generation, QR verification URL generation, DOB-inwords interpolation, and batch issuance audit trails are in place.',
    launcher: true,
  },
  {
    id: 'idCards',
    label: 'Student ID Card Studio',
    shortLabel: 'ID Cards',
    description: 'Filter, design, batch-prepare and print verified student identity cards',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Strict cohort filters, stable selections, bounded concurrent photo preparation and print-range safeguards are regression-checked.',
    launcher: true,
  },
  {
    id: 'gkTest',
    label: 'Competitive Exams & OMR',
    shortLabel: 'Exams & OMR',
    description: 'Registrations, admit cards, centres and OMR workflows',
    category: 'Records & Registers',
    maturity: 'optimized',
    maturityNote: 'Unified competitive test hub, automated admit card PDF generation, OMR registrations indexing, and audit logging are regression-checked.',
    launcher: true,
  },
  {
    id: 'controls',
    label: 'Academic Controls & Subjects',
    shortLabel: 'Controls',
    description: 'Admission windows, sessions, subjects and institution rules',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Atomic session controls, admission window toggles, and audited configuration safeguards are regression-checked.',
    launcher: true,
  },
  {
    id: 'subjects',
    label: 'Subject Rules & Streams',
    shortLabel: 'Subject Rules',
    description: 'Configure streams, subject groups and selection limits',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Stream-subject rule enforcement, multi-group constraints, and live admission validation are in place.',
    launcher: false,
  },
  {
    id: 'practicals',
    label: 'Practicals & Award Rolls',
    shortLabel: 'Practicals',
    description: 'Practical marks, examiners, locking and award rolls',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Validated practical marks bounds, consolidated award roll generation, spreadsheet reconciliation, and audit logging are regression-checked.',
    launcher: true,
  },
  {
    id: 'attendanceMgmt',
    label: 'Student Attendance',
    shortLabel: 'Attendance',
    description: 'Daily attendance registers, entry and reports',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Aggregated attendance tracking, subject-wise grouping, cached register queries, and configuration safeguards are regression-checked.',
    launcher: true,
  },
  {
    id: 'rollNo',
    label: 'Class Roll Number Manager',
    shortLabel: 'Roll Numbers',
    description: 'Assign, validate and sequence class roll numbers',
    category: 'Academics & Controls',
    maturity: 'optimized',
    maturityNote: 'Exact-record updates and approved-record safeguards are in place.',
    launcher: true,
  },
  {
    id: 'mergeStudio',
    label: 'Application Merge & Deduplication',
    shortLabel: 'Merge Studio',
    description: 'Compare and merge duplicate applications by verified identity',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Disjoint-set union clustering, canonical scoring, Recycle Bin safe backup, and audit logging are regression-checked.',
    launcher: true,
  },
  {
    id: 'automations',
    label: 'Communications & Automations',
    shortLabel: 'Automations',
    description: 'Group email, parent notifications and delivery logs',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Rich-text group notifications, real-time recipient filtering, test flight previews, and delivery audit logging are regression-checked.',
    launcher: true,
  },
  {
    id: 'funds',
    label: 'Funds & Fee Accounts',
    shortLabel: 'Fee Accounts',
    description: 'Reconciled fee structures, student ledgers and account distribution',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Atomic account configuration, live ledger synchronization and over-distribution safeguards are regression-checked.',
    launcher: true,
  },
  {
    id: 'accounts',
    label: 'School Accounts, Salaries & Staff Tax',
    shortLabel: 'Accounts',
    description: 'Staff income tax calculator, salary statements, fiscal planning and accounts clerk workflows',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Dedicated accounts clerk workspace, IT calculation engine, tax deductions and salary record management.',
    launcher: true,
  },
  {
    id: 'cms',
    label: 'Website CMS & Administration',
    shortLabel: 'Website CMS',
    description: 'Public website content, hero slideshow, notices, custom pages and recycle bin',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Public and private website controls, notices, slideshow, custom pages, and central recycle bin.',
    launcher: true,
  },
  {
    id: 'ingestion',
    label: 'Direct Entry & CSV Import',
    shortLabel: 'Direct Entry',
    description: 'Express record creation and reviewed bulk data import',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'End-to-end optimized with immediate cohort validation, identity correlation, and auto-rollback protection.',
    launcher: false,
  },
  {
    id: 'boardSync',
    label: 'Board Data Sync (JKBOSE)',
    shortLabel: 'Board Sync',
    description: 'Bulk overwrite student admission fields with verified JKBOSE board data',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'End-to-end optimized with 100% authoritative Board Reg matching, protected class roll numbers, and 30-day rollback memory.',
    launcher: true,
  },
  {
    id: 'adminMgmt',
    label: 'Administrator Access & Permissions',
    shortLabel: 'Admin Access',
    description: 'Manage staff accounts, roles and module permissions',
    category: 'Operations & Automation',
    maturity: 'optimized',
    maturityNote: 'Role-based access controls, module permission matrix, bootstrap superadmin safeguards, and audit logging are regression-checked.',
    launcher: false,
  },
]);

export function getModuleMaturity(maturity) {
  return MODULE_MATURITY[maturity] || MODULE_MATURITY.beta;
}

export function getAdminModule(moduleId) {
  return ADMIN_MODULE_CATALOG.find(module => module.id === moduleId) || null;
}
