// =================================================================
// HSS SHANGUS — Clerk Official Documents & Staff Letterhead Workspace
// Houses Staff Letterhead Writer (Mail Merge), Custom Staff Rosters & Clerk-Scoped History
// =================================================================

import React, { useState, useEffect } from 'react';
import {
  FileText, FileSpreadsheet, History, Printer, Trash2,
  Eye, RefreshCw, Calendar, Users, CheckCircle2, AlertCircle,
  X, Download, ArrowRight, Shield
} from 'lucide-react';
import StaffLetterheadWriterView from './StaffLetterheadWriterView';
import CustomStaffRosterBuilderView from './CustomStaffRosterBuilderView';
import {
  fetchGeneratedDocHistory,
  deleteGeneratedDocFromHistory
} from '../../services/docHistoryService';
import { showToast } from '../../components/common/GlobalToast';
import { sanitizeRichHtml } from '../../utils/sanitizeRichHtml';

export default function ClerkStaffDocumentsWorkspace({
  faculty = [],
  user = null,
  settings = {}
}) {
  const [activeSubTab, setActiveSubTab] = useState('letterhead'); // 'letterhead', 'roster', 'history'

  // History State
  const [historyItems, setHistoryItems] = useState([]);
  const [loadingHistory, setLoadingHistory] = useState(false);
  const [selectedSnapshotDoc, setSelectedSnapshotDoc] = useState(null);

  // Load History Scoped to Accounts Clerk
  const loadClerkHistory = async () => {
    try {
      setLoadingHistory(true);
      const allDocs = await fetchGeneratedDocHistory({ docType: 'all', limitCount: 300 });

      // Strict Clerk Scoping: Only documents generated by Accounts Clerk
      const clerkOnly = (allDocs || []).filter(d => {
        const isClerkDocType = d.docType === 'clerk_staff_letter' || d.docType === 'clerk_staff_roster';
        const isClerkScope = d.extraData?.authorScope === 'accounts_clerk' || d.extraData?.authorRole === 'clerk';
        return isClerkDocType || isClerkScope;
      });

      setHistoryItems(clerkOnly);
    } catch (err) {
      console.error('Failed to load clerk history:', err);
      showToast('Could not load clerk dispatch history: ' + err.message, 'warning');
    } finally {
      setLoadingHistory(false);
    }
  };

  useEffect(() => {
    if (activeSubTab === 'history') {
      loadClerkHistory();
    }
  }, [activeSubTab]);

  // Delete History Record
  const handleDeleteHistory = async (id, title) => {
    if (!window.confirm(`Delete record "${title}" from your clerk dispatch history?`)) return;
    try {
      await deleteGeneratedDocFromHistory(id);
      setHistoryItems(prev => prev.filter(item => item.id !== id));
      showToast('Record removed from history.', 'info');
    } catch (err) {
      showToast('Could not delete record: ' + err.message, 'error');
    }
  };

  // Re-print Snapshot using iframe
  const handlePrintSnapshot = (docItem) => {
    const existing = document.getElementById('clerk-snapshot-print-frame');
    if (existing) existing.remove();

    const iframe = document.createElement('iframe');
    iframe.id = 'clerk-snapshot-print-frame';
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);

    const doc = iframe.contentWindow.document;
    doc.open();
    doc.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${docItem.title || 'Official Document'}</title>
        <style>
          @page { size: A4 portrait; margin: 0.5in; }
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; font-size: 12px; margin: 0; padding: 0; }
        </style>
      </head>
      <body>
        ${docItem.bodyHtml || ''}
      </body>
      </html>
    `);
    doc.close();

    iframe.contentWindow.focus();
    setTimeout(() => {
      try {
        iframe.contentWindow.print();
      } catch (e) {
        console.error('Print snapshot error:', e);
      }
    }, 400);
  };

  return (
    <div className="space-y-3">
      {/* ─── SUB-NAVIGATION BAR (LETTERHEAD WRITER | STAFF ROSTERS | CLERK HISTORY) ─── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 p-1 sm:p-1.5 rounded-xl bg-slate-100/90 dark:bg-slate-950/80 border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-1 overflow-x-auto no-scrollbar">
          <button
            type="button"
            onClick={() => setActiveSubTab('letterhead')}
            className={`px-3 py-1.5 rounded-lg text-xs font-black flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
              activeSubTab === 'letterhead'
                ? 'bg-amber-600 text-white shadow-xs'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200/60 dark:hover:bg-slate-800'
            }`}
          >
            <FileText size={13} />
            <span>Official Letterhead &amp; Mail Merge</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSubTab('roster')}
            className={`px-3 py-1.5 rounded-lg text-xs font-black flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
              activeSubTab === 'roster'
                ? 'bg-amber-600 text-white shadow-xs'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200/60 dark:hover:bg-slate-800'
            }`}
          >
            <FileSpreadsheet size={13} />
            <span>Custom Staff Registers &amp; Rosters</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSubTab('history')}
            className={`px-3 py-1.5 rounded-lg text-xs font-black flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
              activeSubTab === 'history'
                ? 'bg-amber-600 text-white shadow-xs'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200/60 dark:hover:bg-slate-800'
            }`}
          >
            <History size={13} />
            <span>Clerk Dispatch History</span>
            {historyItems.length > 0 && (
              <span className="px-1.5 py-0.2 rounded-full text-[9px] bg-slate-200 dark:bg-slate-800 text-slate-800 dark:text-slate-200 font-mono">
                {historyItems.length}
              </span>
            )}
          </button>
        </div>

        <div className="flex items-center gap-1 text-[10.5px] text-slate-500 dark:text-slate-400 px-2 shrink-0">
          <Shield size={12} className="text-amber-600 dark:text-amber-500" />
          <span>Accounts Clerk Workspace &bull; Scoped Dispatch</span>
        </div>
      </div>

      {/* ─── SUB-TAB 1: OFFICIAL LETTERHEAD & MAIL MERGE ─── */}
      {activeSubTab === 'letterhead' && (
        <StaffLetterheadWriterView
          faculty={faculty}
          user={user}
          onOpenHistory={() => setActiveSubTab('history')}
        />
      )}

      {/* ─── SUB-TAB 2: CUSTOM STAFF REGISTERS & ROSTERS ─── */}
      {activeSubTab === 'roster' && (
        <CustomStaffRosterBuilderView
          faculty={faculty}
          user={user}
          onOpenHistory={() => setActiveSubTab('history')}
        />
      )}

      {/* ─── SUB-TAB 3: CLERK DISPATCH HISTORY & ARCHIVE ─── */}
      {activeSubTab === 'history' && (
        <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-3 sm:p-4 shadow-2xs space-y-3 animate-fadeIn">
          <div className="flex items-center justify-between pb-2 border-b border-slate-100 dark:border-slate-800">
            <div className="flex items-center gap-2">
              <History size={16} className="text-amber-600 dark:text-amber-500" />
              <div>
                <h2 className="text-sm font-black text-slate-900 dark:text-white">
                  Accounts Clerk Dispatch &amp; Document Archive
                </h2>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">
                  Audit trail and re-print records of all official letters and staff rosters created by the Accounts Clerk.
                </p>
              </div>
            </div>

            <button
              type="button"
              onClick={loadClerkHistory}
              disabled={loadingHistory}
              className="p-1.5 rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 transition-colors cursor-pointer"
              title="Refresh History"
            >
              <RefreshCw size={13} className={loadingHistory ? 'animate-spin' : ''} />
            </button>
          </div>

          {loadingHistory ? (
            <div className="py-12 text-center text-xs text-slate-500 font-semibold">
              Loading clerk dispatch history from cloud...
            </div>
          ) : historyItems.length === 0 ? (
            <div className="py-12 text-center text-slate-400 space-y-2">
              <FileText size={32} className="mx-auto text-slate-300 dark:text-slate-700" />
              <div className="text-xs font-bold text-slate-600 dark:text-slate-400">No clerk documents in history yet</div>
              <p className="text-[11px] text-slate-400 max-w-sm mx-auto">
                Generate official letters or staff registers from the tabs above. They will be archived here automatically for instant re-printing.
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800">
              <table className="w-full text-left text-xs divide-y divide-slate-200 dark:divide-slate-800">
                <thead className="bg-slate-50 dark:bg-slate-800/60 font-extrabold text-slate-700 dark:text-slate-300">
                  <tr>
                    <th className="p-2.5">Date &amp; Ref No.</th>
                    <th className="p-2.5">Document Title</th>
                    <th className="p-2.5">Type</th>
                    <th className="p-2.5">Recipient / Scope</th>
                    <th className="p-2.5 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 text-slate-800 dark:text-slate-200">
                  {historyItems.map((item) => (
                    <tr key={item.id} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/40">
                      <td className="p-2.5 whitespace-nowrap">
                        <div className="font-extrabold text-slate-900 dark:text-white">
                          {item.dateStr || new Date(item.createdAt).toLocaleDateString('en-GB')}
                        </div>
                        <div className="text-[10px] font-mono text-slate-500">
                          {item.refNo || '—'}
                        </div>
                      </td>
                      <td className="p-2.5 font-bold">
                        {item.title}
                      </td>
                      <td className="p-2.5 whitespace-nowrap">
                        <span className={`px-2 py-0.5 rounded-full text-[9.5px] font-black ${
                          item.docType === 'clerk_staff_letter'
                            ? 'bg-amber-100 dark:bg-amber-950/60 text-amber-800 dark:text-amber-300 border border-amber-200 dark:border-amber-800'
                            : 'bg-indigo-100 dark:bg-indigo-950/60 text-indigo-800 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800'
                        }`}>
                          {item.docType === 'clerk_staff_letter' ? 'Letterhead Mail Merge' : 'Staff Register Roster'}
                        </span>
                      </td>
                      <td className="p-2.5 text-slate-600 dark:text-slate-400">
                        {item.recipientOrStudent || 'Selected Staff'}
                      </td>
                      <td className="p-2.5 text-right whitespace-nowrap">
                        <div className="flex items-center justify-end gap-1.5">
                          <button
                            type="button"
                            onClick={() => setSelectedSnapshotDoc(item)}
                            className="p-1 rounded text-slate-600 hover:text-amber-600 dark:text-slate-400 dark:hover:text-amber-400 hover:bg-slate-100 dark:hover:bg-slate-800 cursor-pointer"
                            title="View Snapshot"
                          >
                            <Eye size={13} />
                          </button>

                          <button
                            type="button"
                            onClick={() => handlePrintSnapshot(item)}
                            className="p-1 rounded text-slate-600 hover:text-amber-600 dark:text-slate-400 dark:hover:text-amber-400 hover:bg-slate-100 dark:hover:bg-slate-800 cursor-pointer"
                            title="Re-Print"
                          >
                            <Printer size={13} />
                          </button>

                          <button
                            type="button"
                            onClick={() => handleDeleteHistory(item.id, item.title)}
                            className="p-1 rounded text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 cursor-pointer"
                            title="Delete"
                          >
                            <Trash2 size={13} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* ─── SNAPSHOT PREVIEW MODAL ─── */}
      {selectedSnapshotDoc && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/60 backdrop-blur-xs animate-fadeIn">
          <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-2xl max-w-3xl w-full max-h-[90vh] flex flex-col overflow-hidden">
            <div className="p-3.5 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between">
              <div>
                <h3 className="font-black text-sm text-slate-900 dark:text-white">
                  {selectedSnapshotDoc.title}
                </h3>
                <span className="text-[10px] text-slate-500 font-mono">
                  Ref: {selectedSnapshotDoc.refNo} &bull; Date: {selectedSnapshotDoc.dateStr}
                </span>
              </div>

              <div className="flex items-center gap-1.5">
                <button
                  type="button"
                  onClick={() => handlePrintSnapshot(selectedSnapshotDoc)}
                  className="px-2.5 py-1 text-xs font-black bg-amber-600 hover:bg-amber-500 text-white rounded-lg flex items-center gap-1 cursor-pointer"
                >
                  <Printer size={12} />
                  <span>Re-Print</span>
                </button>

                <button
                  type="button"
                  onClick={() => setSelectedSnapshotDoc(null)}
                  className="p-1 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 cursor-pointer"
                >
                  <X size={16} />
                </button>
              </div>
            </div>

            <div className="p-5 overflow-y-auto flex-1 bg-slate-50 dark:bg-slate-950">
              <div
                dangerouslySetInnerHTML={{ __html: sanitizeRichHtml(selectedSnapshotDoc.bodyHtml || '') }}
                className="bg-white p-6 rounded-lg shadow-sm border border-slate-300 text-slate-900 text-xs sm:text-sm leading-relaxed"
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
