import React from 'react';
import { FileText, ShieldAlert, CreditCard, Scale, CheckCircle2 } from 'lucide-react';
import SEO from '../components/SEO';

export default function TermsAndConditions() {
  return (
    <div className="w-full bg-slate-50 min-h-screen py-10 sm:py-14 text-slate-700">
      <SEO 
        title="Terms and Conditions" 
        description="Official Terms and Conditions for Govt. Higher Secondary School Shangus. Read terms regarding portal usage, fee payments in INR, user accounts, and school policies."
      />
      
      <div className="max-w-4xl mx-auto px-4 sm:px-6">
        
        {/* Page Header */}
        <div className="bg-white p-6 sm:p-10 rounded-3xl shadow-sm border border-slate-200/80 mb-8 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-40 h-40 bg-teal-500/5 rounded-bl-full pointer-events-none" />
          <div className="flex items-center gap-3 text-teal-600 mb-3">
            <FileText size={28} className="stroke-[2]" />
            <span className="text-xs font-bold uppercase tracking-widest">Portal Usage & Legal Agreement</span>
          </div>
          <h1 className="text-2xl sm:text-4xl font-extrabold text-slate-900 tracking-tight mb-3">
            Terms and Conditions
          </h1>
          <p className="text-sm sm:text-base text-slate-500 leading-relaxed">
            Welcome to the official online web portal of Govt. Higher Secondary School Shangus ("School", "Institution", "We", or "Us"). By accessing, browsing, registering, or making payments through this website, you agree to comply with and be bound by the following Terms and Conditions.
          </p>
          <div className="mt-4 pt-4 border-t border-slate-100 flex flex-wrap items-center justify-between text-xs text-slate-400 gap-2">
            <span><strong>Effective Date:</strong> June 28, 2026</span>
            <span><strong>Last Revised:</strong> July 22, 2026</span>
          </div>
        </div>

        {/* Content Body */}
        <div className="bg-white p-6 sm:p-10 rounded-3xl shadow-sm border border-slate-200/80 space-y-8 text-sm sm:text-base leading-relaxed">
          
          {/* Section 1 */}
          <section>
            <h2 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 flex items-center gap-2">
              <span className="w-7 h-7 rounded-lg bg-teal-100 text-teal-700 text-xs flex items-center justify-center font-extrabold">1</span>
              Services Provided
            </h2>
            <p className="text-slate-600 mb-3">
              This website provides educational and administrative digital services for students, parents, and applicants of Govt. Higher Secondary School Shangus, including:
            </p>
            <ul className="space-y-2 pl-2">
              <li className="flex items-start gap-2">
                <CheckCircle2 size={16} className="text-teal-600 mt-1 flex-shrink-0" />
                <span>Online Student Registration & Admission Application for Secondary and Higher Secondary streams (Class 9th, 10th, 11th, and 12th).</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 size={16} className="text-teal-600 mt-1 flex-shrink-0" />
                <span>Online Fee Payment processing (Session Admission Fees, Examination Fees, Prospectus & Verification Charges).</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 size={16} className="text-teal-600 mt-1 flex-shrink-0" />
                <span>Publishing official Academic Notices, Date Sheets, Circulars, and Examination Results.</span>
              </li>
            </ul>
          </section>

          {/* Section 2 */}
          <section className="p-5 bg-slate-50 rounded-2xl border border-slate-200/80">
            <h2 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 flex items-center gap-2">
              <CreditCard size={20} className="text-teal-600" />
              Fee Structure, Currency & Payment Terms
            </h2>
            <div className="space-y-3 text-slate-600">
              <p><strong>Currency:</strong> All fees, charges, and rates quoted on this website are in <strong>Indian Rupees (INR ₹)</strong>.</p>
              <p><strong>Fee Schedules:</strong> Admission fees for various academic streams (Science, Humanities, Secondary) are determined as per institutional rules approved by the Department of School Education J&K and are explicitly displayed on the Admissions page.</p>
              <p><strong>Payment Authorization:</strong> When making a payment on our portal, you certify that you are the authorized holder of the payment account/card or have explicit permission from the account holder to perform the transaction.</p>
              <p><strong>Transaction Confirmation:</strong> A transaction is deemed successful only when a valid electronic transaction ID and receipt status are generated by the payment gateway and reconciled on our system.</p>
            </div>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 flex items-center gap-2">
              <span className="w-7 h-7 rounded-lg bg-teal-100 text-teal-700 text-xs flex items-center justify-center font-extrabold">3</span>
              Accuracy of User Data & Falsification
            </h2>
            <p className="text-slate-600 leading-relaxed mb-3">
              Applicants and guardians are solely responsible for ensuring that all information submitted during registration (including marks obtained, category certificates, date of birth, and identity credentials) is accurate, current, and genuine.
            </p>
            <div className="p-4 bg-amber-50 border border-amber-200 text-amber-900 rounded-xl text-xs sm:text-sm flex items-start gap-2.5">
              <ShieldAlert size={18} className="text-amber-600 mt-0.5 flex-shrink-0" />
              <span><strong>Notice:</strong> Submission of fraudulent documents, inaccurate marks cards, or forged credentials will result in immediate disqualification and cancellation of admission without any refund.</span>
            </div>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 flex items-center gap-2">
              <span className="w-7 h-7 rounded-lg bg-teal-100 text-teal-700 text-xs flex items-center justify-center font-extrabold">4</span>
              System Security & Prohibited Conduct
            </h2>
            <p className="text-slate-600 mb-2">Users are strictly prohibited from:</p>
            <ul className="list-disc pl-6 space-y-1.5 text-slate-600">
              <li>Attempting to gain unauthorized access to administrative consoles, server databases, or user accounts.</li>
              <li>Executing automated web-scraping, denial-of-service (DoS) attacks, or security vulnerabilities probing.</li>
              <li>Misusing official digital receipts or generating falsified roll numbers.</li>
            </ul>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 flex items-center gap-2">
              <span className="w-7 h-7 rounded-lg bg-teal-100 text-teal-700 text-xs flex items-center justify-center font-extrabold">5</span>
              Intellectual Property
            </h2>
            <p className="text-slate-600 leading-relaxed">
              All website content, logos, institutional crests, layout designs, digital PDF formats, and custom source code are the intellectual property of Govt. Higher Secondary School Shangus and its development partners (Next Life Technologies). Unauthorized copying, republication, or distribution without prior written consent is forbidden.
            </p>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 flex items-center gap-2">
              <span className="w-7 h-7 rounded-lg bg-teal-100 text-teal-700 text-xs flex items-center justify-center font-extrabold">6</span>
              Limitation of Liability & External Links
            </h2>
            <p className="text-slate-600 leading-relaxed">
              Govt. HSS Shangus shall not be held liable for temporary website downtime, internet banking network delays, payment gateway failures, or technical interruptions beyond our control. Users are advised to initiate fee payments well in advance of closing dates.
            </p>
          </section>

          {/* Section 7 */}
          <section className="pt-4 border-t border-slate-100">
            <h2 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 flex items-center gap-2">
              <Scale size={20} className="text-teal-600" />
              Governing Law & Jurisdiction
            </h2>
            <p className="text-slate-600 leading-relaxed mb-4">
              These Terms and Conditions shall be governed by and construed in accordance with the laws of the Union Territory of Jammu & Kashmir and the Republic of India. Any disputes arising out of or in connection with the portal or fee payments shall be subject to the exclusive jurisdiction of the competent courts in <strong>District Anantnag, Jammu & Kashmir, India</strong>.
            </p>
            <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200/80 text-xs sm:text-sm text-slate-700 space-y-1">
              <p className="text-slate-900 font-bold text-sm sm:text-base">Contact Department:</p>
              <p className="font-semibold text-slate-800">Admissions & Administration Office, Govt. Higher Secondary School Shangus</p>
              <p className="text-slate-600">Email: <a href="mailto:adm.exam.hss.shangus@gmail.com" className="text-teal-700 font-bold hover:underline">adm.exam.hss.shangus@gmail.com</a></p>
            </div>
          </section>

        </div>
      </div>
    </div>
  );
}
